### ISSUE TITLE
Custom image URL

### ISSUE THREAD

**Issue by igoratsok** [RonnyWeiss/APEX-Unleash-RichTextEditor#1]
Hi,
This plug-in is just great, congrats and thanks for it.

There's something I wanna do, anyways. I usually don't host my images in a blob. When I upload them, I host them in a CDN, and, then, i just save the URL referencing the image at the database.

Your plug-in would work awesomely for that, except that it uses the PRINT_IMAGE procedure to obtain the images.

Actually, for me, I'd simply replace this:

```
var imgSRC = apex.server.pluginUrl(pOpts.ajaxID, {
                    x01: "PRINT_IMAGE",
                    x02: pPK,
                    pageItems: items2SubmitImgDown
                });
```

For this:

`var imgSRC = pPK;`

And then I'd set in "Execute on Image Upload" :P_OUT_PK := MY_URL_CDN

And it would work great for my purposes.

But do you think it would be a good plug-in option? If you want, I can do it, and then I can fork and then pull request. What do you think?

Thanks!

**Comment by RonnyWeiss** [comment]
Hello

Great to hear that you use my plug-in and that you also build your own customization. It's fun to build plug-ins and get cool feedback. Please feel free to tweet about it and strengthen the community!

Your Idea is also great and I will add this option to the plug-in. I only have some questions?

How will you add the images? do you upload them when they are pasted or dropped with my plug-in or is the plug-in just for rendering?

Because image can now already be added by RTE. E.g. when you copy a image from a website like a wikipedia page then images are added as reference. So maybe I need more details about what you wanna do?

But thank you very much for Feedback.

Hope to hear from ou again.

Best regards

Ronny

**Comment by RonnyWeiss** [comment]
Can you explain the usecase more detailed? are the images uploaded ith unleash rte or just shown?
