### ISSUE TITLE
Images are not displayed in RTE

### ISSUE THREAD

**Issue by murugusr** [RonnyWeiss/APEX-Unleash-RichTextEditor#10]
Hi Ronny,
Thanks for this plugin. This plugin serves the purpose perfectly. i am facing an issue when I drag and drop images, the image is being uploaded to collection or table but the image link looks broken (the image is not displayed). i made lots attempts to figure out by refering your sample application but still the same issue. I finally copied the page from my application to your sample application now the image is being displayed. Is there any settings or configurations at the application level and possibly be missing in my application?? 
Thanks for your help in advance.

**Comment by RonnyWeiss** [comment]
Hello

can you please give me some more details about your code or what you've done in your app?

What do you mean the link looks broken? Do you have an example?

A short info is that when you upload clob with images the links where cleanded because they just work for current session. When you want to show the images e.g. in a report without unleash rte plug-in then you have to use clob load 2 plug-in. This can render the images everywhere because it uses same mechanism.

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Closed because no answer was given
