### ISSUE TITLE
Using CRTL-V loads always the first image

### ISSUE THREAD

**Issue by dinbrasil** [RonnyWeiss/APEX-Unleash-RichTextEditor#11]
Hi, Ronny, 
This plugin is really great, but I found a bug.

When I paste an image (screen capture)  using cmd-V for the first time, the image is pasted and uploaded to clob.
But I repeat the paste with another image, the first image is pasted again. 

I tested on Chrome and Firefox, using a macbook, Apex 20.2.
It happens on your demo app too. 

Maybe it is something with 20.2. 

Regards, 
Cezar Rosaneli

**Comment by RonnyWeiss** [comment]
Hello Thank you for the issue. I will check that and hope that I can fix that.

**Comment by RonnyWeiss** [comment]
Hello thats just a minor bug in my sample App is is now fixed. Because as pk I used image file name. ON CTRL-V its everytime the same. Not I use the file-name and a random string ;-). In Real life you would use a ident sequence but I did not want to make a sequence just for this small example ;-)

But thank you for the issue!!! Have fun with my plugins
