### ISSUE TITLE
issue when using friendly urls in APEX 20.1

### ISSUE THREAD

**Issue by dgielis** [RonnyWeiss/APEX-Unleash-RichTextEditor#8]
Hi Ronny,

Love the plugin. I saw when I was building an APEX 20.1 app, which had friendly urls turned on, there's an extra request being done by APEX which breaks the plug-in.
<img width="1065" alt="Screenshot 2020-05-05 at 21 57 53" src="https://user-images.githubusercontent.com/703891/81110239-8ebf1d80-8f1b-11ea-9c25-1adba657a6d0.png">

As you can see in the screenshot, there's an extra request which puts the friendly structure around wwv_flow.show.

Not sure it's an APEX bug or as plug-in developers we can deal with it.

Thanks,
Dimitri

**Comment by dgielis** [comment]
there's one more issue with the plugin ; that it adds < p > &nbsp; </p>

**Comment by RonnyWeiss** [comment]
Hello Dimitri

Friendly URLs are working with the plug-in on apex.oracle.com. I chaned my App to friendly urls and it's working fine. But your're right with that <p> bug and I will fix that that. 

Are there anyp patches for APEX 20.0 that maybe needed to fix the url issue? How did you add the plug-in?

I have a RTE and load the plug-in on page load. The RTE does not have any source. The content is loaded by the RTE! That is importent because only then the urls are changed. URLs are working only for one session, because of session id, so it's very important that plugin has the change to change the url on runtime. Maybe that's the bug you have whn logging out.

Hope I can help you?

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
the <p> bug is fixed in version 2.0.3. Could you fix the others problems? Because for the url processing I just use apex.server.plugin. So I think the APEX Team has also updated this API for friendly URLS and on apex.oracle.com it's working. I have copied my sample app and activate friendly urls there: https://apex.oracle.com/pls/apex/ronnyweiss_outlook_com/r/rwplugins148038/26
